name: Generate Celestial Events

on:
  workflow_dispatch:     # Manual trigger
  schedule:
    - cron: '0 6 * * 0'   # Every Sunday at 6:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generator script
        run: node generate-events.js

      - name: Commit and push updated events.json
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data/events.json
          git commit -m "Auto-update events.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
